Added Popover, Tooltip, and Tabs
RobotsAndPencils/react-robits pull request #28
Opened 2021-02-24 21:46 UTC by depiction

This adds the following components to Robits from the Unshuffled project. I converted the Popover and Tooltip components from class components to functional components. The Tabs component was already a functional component.

I've noticed that Storybook doesn't always load components properly. I sometimes have to switch from the canvas to docs tab, then back to the canvas tab for the component to load and work properly.

2021-02-25 18:39 UTC, dfagan2 requested changes
Looking great, nice work. Just a couple things..

2021-02-25 18:39 UTC, dfagan2 commented on src/core/components/popover/popover_talentPortal.module.scss
> +  // @include reset-text();
i know this is copy-paste and leftover, but we can remove it

2021-02-25 18:39 UTC, dfagan2 commented on src/core/components/popover/Popover.js
> +  const classes = classNames(innerClassName)
is this translation through `classNames` needed? could `innerClassName` be applied directly?

2021-02-25 18:39 UTC, dfagan2 commented on src/core/components/tabs/Tabs.js
> +  options = [],
if I'm remembering correctly, I believe in order for the docs tab to successfully pull in this information, it has to be pulled out into a dedicated `Tabs.propTypes = {}` definition at the bottom of the file like we are doing elsewhere. Hopefully that change fixes the missing info and "unknowns" here:
<img width="1160" alt="Screen Shot 2021-02-25 at 1 14 41 PM" src="https://user-images.githubusercontent.com/769972/109199742-cda1b680-776d-11eb-8f4a-ba304039b3fd.png">

2021-02-25 18:39 UTC, dfagan2 commented on src/core/components/tooltip/Tooltip.js
> +      removeListeners()
This unmount is pretty consistently throwing the below error. Like when you navigate away from the Tooltips story, a second or two later the new story you landed on errors. Could add some optional chaining there to help prevent that error, but may be a better way?
<img width="1065" alt="Screen Shot 2021-02-25 at 1 13 31 PM" src="https://user-images.githubusercontent.com/769972/109200131-3c7f0f80-776e-11eb-8f1e-2eca5e9620a7.png">

2021-02-25 18:39 UTC, dfagan2 commented on src/core/components/tooltip/Tooltip.js
> +  const classes = classNames(styling['tooltip-inner'], innerClassName)
`innerContentClasses` would be a better name here

2021-02-25 18:39 UTC, dfagan2 commented on src/core/components/tooltip/tooltip_talentPortal.module.scss
> +  // So reset our font and text properties to avoid inheriting weird values.
the above 2 comment lines can be deleted

2021-02-26 19:09 UTC, dfagan2 approved these changes
There are some unused imports in `Tabs.stories.js`, then we can merge

2021-02-26 20:25 UTC, depiction commented
@dfagan2 I removed the unused imports. Github won't let me merge this until you approve it again.

2021-02-26 20:52 UTC, dfagan2 approved these changes

2021-03-01 14:20 UTC, merged